### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by oh2th** [oh2th/com.go-e.charger#12]
Verify / Translate "fr" objects in [translations](https://github.com/oh2th/com.go-e.charger/tree/main/.translation)-directory.

**Comment by oh2th** [comment]
Now I am getting the translations :)

**Comment by Picsou621** [comment]
Great! So I'm going to check it all out again tonight once the whole family
is in bed ;-)


Le dim. 8 janv. 2023 à 11:43, Tapio Heiskanen ***@***.***> a
écrit :

**Comment by oh2th** [comment]
At least now when you are a contributor you have a bit more privileges.
