### ISSUE TITLE
No flow actions listed under “Then” 

### ISSUE THREAD

**Issue by MaikelKelder** [oh2th/com.go-e.charger#13]
**Describe the bug**
Directly after installation I have seen the actions turn on/turn off but after a minute or so when creating a flow, no actions are displayed. For “If/And” actions are listed, but also had those disappeared ones.

**To Reproduce**
1. Clean install of app
2. Create a flow 
3. Choose “new card” new ticket?
4. Under “Then” go to Go-e charger
5. Empty list displayed

**Expected behavior**
At least 2 choices displayed “turn on” and “turn off”

**Screenshots**
Can add later if needed

**Desktop (please complete the following information):**
 - OS: iOS latest (Jan 2023) 16.1.1
- Homey app latest 8.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 13 
 - OS: [e.g. iOS 16.1.1
 - Browser chrome (not used)

**Additional context**

**Comment by oh2th** [comment]
Thank you for your report.

Which device did you use to pair your go-eCharger?

<img width="576" alt="Screenshot 2023-01-08 at 11 36 37" src="https://user-images.githubusercontent.com/59442255/211189316-28ffa5c4-947f-4c5e-b8c0-8558df84072a.png">

All flow cards are device specific, there is no app-level flow cards in this new version.

**Comment by MaikelKelder** [comment]
It’s the v2 version with fixed ip addres.

**Comment by oh2th** [comment]
Ah, Then... cards, you are using "classic flow", yes? This actually has been corrected in the test version already.

There was an advanced flow feature in the Then cards called tokens, that are not supported in classic flows. So I have made an update to fix this issue, but not yet released.

Could you install https://homey.app/en-us/app/com.go-e.charger/go-e-Charger/test/ and see how it works.

**Comment by MaikelKelder** [comment]
Yes, the device now shows in all if/and/then, but not directly after
install, but after a manual restart of the app, before restart it only
showed in IF.
Seems a bit random sometimes, but for now it’s 👍 ok.

**Comment by oh2th** [comment]
Ok, I will close this now, lets keep an eye on it anyway if behaves weirdly still.
