### ISSUE TITLE
Fronius wattpilot

### ISSUE THREAD

**Issue by Owein1977** [oh2th/com.go-e.charger#24]
Hi!

is there a chance or plan to extend the app for Fronius wattpilot?
Since there is Nieder-Olm communication for 11kw wallbox it wld be great to sync my car (Audi, already exists) with the wallbox
Cheers a thx
Oli

**Comment by oh2th** [comment]
I'm sorry. Fronius has their custom firmware on the device and is not compatible with go-e Charger APIs.
This was earlier discussed in Homey Community forum also
https://community.homey.app/t/app-pro-go-e-charger/74195/30?u=oh2th
